// ============================
// DADOS DOS PRODUTOS
// ============================

const produtos = [

{ nome: "Arroz", categoria: "Mercearia" },
{ nome: "Feijão", categoria: "Mercearia" },
{ nome: "Macarrão", categoria: "Mercearia" },
{ nome: "Óleo de Soja", categoria: "Mercearia" },
{ nome: "Azeite de Oliva", categoria: "Mercearia" },
{ nome: "Farinha de Trigo", categoria: "Mercearia" },
{ nome: "Farinha de Mandioca", categoria: "Mercearia" },
{ nome: "Farinha de Rosca", categoria: "Mercearia" },
{ nome: "Fubá", categoria: "Mercearia" },
{ nome: "Amido de Milho", categoria: "Mercearia" },
{ nome: "Açúcar", categoria: "Mercearia" },
{ nome: "Açúcar Mascavo", categoria: "Mercearia" },
{ nome: "Café", categoria: "Mercearia" },
{ nome: "Milho Verde", categoria: "Mercearia" },
{ nome: "Ervilha", categoria: "Mercearia" },
{ nome: "Molho de Tomate", categoria: "Mercearia" },
{ nome: "Extrato de Tomate", categoria: "Mercearia" },
{ nome: "Atum", categoria: "Mercearia" },
{ nome: "Sardinha", categoria: "Mercearia" },

{ nome: "Sal", categoria: "Temperos e Condimentos" },
{ nome: "Pimenta do Reino", categoria: "Temperos e Condimentos" },
{ nome: "Páprica Defumada", categoria: "Temperos e Condimentos" },
{ nome: "Páprica Doce", categoria: "Temperos e Condimentos" },
{ nome: "Páprica Picante", categoria: "Temperos e Condimentos" },
{ nome: "Orégano", categoria: "Temperos e Condimentos" },
{ nome: "Cominho", categoria: "Temperos e Condimentos" },
{ nome: "Canela em Pau", categoria: "Temperos e Condimentos" },
{ nome: "Canela em Pó", categoria: "Temperos e Condimentos" },
{ nome: "Mostarda", categoria: "Temperos e Condimentos" },
{ nome: "Ketchup", categoria: "Temperos e Condimentos" },
{ nome: "Maionese", categoria: "Temperos e Condimentos" },
{ nome: "Shoyu", categoria: "Temperos e Condimentos" },
{ nome: "Vinagre", categoria: "Temperos e Condimentos" },

{ nome: "Banana", categoria: "Hortifruti" },
{ nome: "Maçã", categoria: "Hortifruti" },
{ nome: "Laranja", categoria: "Hortifruti" },
{ nome: "Limão", categoria: "Hortifruti" },
{ nome: "Abacaxi", categoria: "Hortifruti" },
{ nome: "Mamão", categoria: "Hortifruti" },
{ nome: "Batata", categoria: "Hortifruti" },
{ nome: "Batata Doce", categoria: "Hortifruti" },
{ nome: "Cebola", categoria: "Hortifruti" },
{ nome: "Alho", categoria: "Hortifruti" },
{ nome: "Tomate", categoria: "Hortifruti" },
{ nome: "Alface", categoria: "Hortifruti" },
{ nome: "Repolho", categoria: "Hortifruti" },
{ nome: "Cenoura", categoria: "Hortifruti" },
{ nome: "Pepino", categoria: "Hortifruti" },
{ nome: "Pimentão Verde", categoria: "Hortifruti" },
{ nome: "Pimentão Vermelho", categoria: "Hortifruti" },
{ nome: "Pimentão Amarelo", categoria: "Hortifruti" },
{ nome: "Abobrinha", categoria: "Hortifruti" },
{ nome: "Berinjela", categoria: "Hortifruti" },
{ nome: "Cheiro Verde", categoria: "Hortifruti" },
{ nome: "Ovos", categoria: "Hortifruti" },

{ nome: "Carne Moída", categoria: "Açougue" },
{ nome: "Acém", categoria: "Açougue" },
{ nome: "Patinho", categoria: "Açougue" },
{ nome: "Coxão Mole", categoria: "Açougue" },
{ nome: "Coxão Duro", categoria: "Açougue" },
{ nome: "Alcatra", categoria: "Açougue" },
{ nome: "Picanha", categoria: "Açougue" },
{ nome: "Costela", categoria: "Açougue" },
{ nome: "Linguiça", categoria: "Açougue" },
{ nome: "Bacon", categoria: "Açougue" },
{ nome: "Filé de Frango", categoria: "Açougue" },
{ nome: "Peito de Frango", categoria: "Açougue" },
{ nome: "Coxa e Sobrecoxa", categoria: "Açougue" },

{ nome: "Filé de Tilápia", categoria: "Peixaria" },
{ nome: "Salmão", categoria: "Peixaria" },
{ nome: "Sardinha Fresca", categoria: "Peixaria" },
{ nome: "Camarão", categoria: "Peixaria" },

{ nome: "Presunto", categoria: "Frios" },
{ nome: "Mussarela", categoria: "Frios" },
{ nome: "Queijo Prato", categoria: "Frios" },
{ nome: "Queijo Minas", categoria: "Frios" },
{ nome: "Queijo Parmesão", categoria: "Frios" },
{ nome: "Mortadela", categoria: "Frios" },
{ nome: "Salame", categoria: "Frios" },
{ nome: "Peito de Peru", categoria: "Frios" },

{ nome: "Leite", categoria: "Laticínios" },
{ nome: "Leite em Pó", categoria: "Laticínios" },
{ nome: "Manteiga", categoria: "Laticínios" },
{ nome: "Margarina", categoria: "Laticínios" },
{ nome: "Requeijão", categoria: "Laticínios" },
{ nome: "Iogurte", categoria: "Laticínios" },
{ nome: "Creme de Leite", categoria: "Laticínios" },

{ nome: "Pão Francês", categoria: "Padaria e Panificação" },
{ nome: "Pão de Forma", categoria: "Padaria e Panificação" },
{ nome: "Pão de Hambúrguer", categoria: "Padaria e Panificação" },
{ nome: "Pão de Hot Dog", categoria: "Padaria e Panificação" },
{ nome: "Massa de Pizza", categoria: "Padaria e Panificação" },

{ nome: "Leite Condensado", categoria: "Doces e Confeitaria" },
{ nome: "Chocolate em Pó", categoria: "Doces e Confeitaria" },
{ nome: "Achocolatado", categoria: "Doces e Confeitaria" },
{ nome: "Gelatina", categoria: "Doces e Confeitaria" },
{ nome: "Doce de Leite", categoria: "Doces e Confeitaria" },
{ nome: "Chocolate ao Leite", categoria: "Doces e Confeitaria" },
{ nome: "Chocolate Amargo", categoria: "Doces e Confeitaria" },
{ nome: "Chocolate ao Branco", categoria: "Doces e Confeitaria" },

{ nome: "Água", categoria: "Bebidas" },
{ nome: "Refrigerante", categoria: "Bebidas" },
{ nome: "Suco", categoria: "Bebidas" },
{ nome: "Cerveja", categoria: "Bebidas" },
{ nome: "Vinho Tinto", categoria: "Bebidas" },
{ nome: "Vinho Branco", categoria: "Bebidas" },
{ nome: "Energético", categoria: "Bebidas" },
{ nome: "Cachaça", categoria: "Bebidas" }

]